create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null auto_increment, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table friend (friend_since bigint, friend_steamid bigint, id bigint not null auto_increment, player_parent_steamid bigint, avatar varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile (appid bigint, game_appid bigint, id bigint not null auto_increment, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, app_name varchar(255), primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
