create table player (steamid bigint not null, community_visibility_state integer not null, person_name varchar(255),comment_permission integer not null, profileurl varchar(255), avatar varchar(255), avatar_medium varchar(255), avatar_full varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
create table achievement (achieved bit not null, game_profile_id bigint, id bigint not null, unlock_time bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table achievement_seq (next_val bigint) engine=InnoDB;
insert into achievement_seq values ( 1 );
create table friend (friend_since bigint, id bigint not null, player_friend_steamid bigint, player_parent_steamid bigint, primary key (id)) engine=InnoDB;
create table friend_seq (next_val bigint) engine=InnoDB;
insert into friend_seq values ( 1 );
create table game (appid bigint not null, name varchar(255), primary key (appid)) engine=InnoDB;
create table game_profile_seq (next_val bigint) engine=InnoDB;
insert into game_profile_seq values ( 1 );
create table game_profile (game_appid bigint, id bigint not null, last_time_played bigint, play_time_disconnected bigint, player_steamid bigint, total_playtime bigint, primary key (id)) engine=InnoDB;
create table player (comment_permission integer not null, community_visibility_state integer not null, steamid bigint not null, avatar varchar(255), avatar_full varchar(255), avatar_medium varchar(255), person_name varchar(255), profileurl varchar(255), real_name varchar(255), primary key (steamid)) engine=InnoDB;
alter table friend add constraint UK_nu5n2tciyeyq8clnyej1e1cjj unique (player_friend_steamid);
alter table achievement add constraint FKdsf7rgqlpr16pf3xuk0yxmx8s foreign key (game_profile_id) references game_profile (id);
alter table friend add constraint FKtfftcefgr1pb67tw5q8cpk31f foreign key (player_friend_steamid) references player (steamid);
alter table friend add constraint FKlg2mrwhfvstmjhqldvwhr73qp foreign key (player_parent_steamid) references player (steamid);
alter table game_profile add constraint FKcs7gjh7i9pr74q3ln3u7jssmq foreign key (game_appid) references game (appid);
alter table game_profile add constraint FKmc3u25gdn5es565thggw4yimb foreign key (player_steamid) references player (steamid);
