alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
alter table achievement drop foreign key FKdsf7rgqlpr16pf3xuk0yxmx8s;
alter table friend drop foreign key FKlg2mrwhfvstmjhqldvwhr73qp;
alter table game_profile drop foreign key FKcs7gjh7i9pr74q3ln3u7jssmq;
alter table game_profile drop foreign key FKmc3u25gdn5es565thggw4yimb;
drop table if exists achievement;
drop table if exists friend;
drop table if exists game;
drop table if exists game_profile;
drop table if exists player;
